[phases.setup]
nixPkgs = ["python39"]

[phases.install]
cmds = ["cd backend && pip install -r requirements-combined.txt"]

[start]
cmd = "cd backend && uvicorn src.api.main:app --host 0.0.0.0 --port $PORT"
